import './globals.css'
import { Inter, Sora, Work_Sans, Sen } from 'next/font/google'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', 
})

const sora = Sora({ 
  subsets: ['latin'],
  variable: '--font-sora', 
})

const work_sans = Work_Sans({ 
  subsets: ['latin'],
  variable: '--font-work-sans', 
})

const sen = Sen({ 
  subsets: ['latin'],
  variable: '--font-sen', 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${sora.variable} ${work_sans.variable} ${sen.variable}`}>
      <body className="font-inter">{children}</body>
    </html>
  )
}
